/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.4.1 src/assets/3d/Computer.glb 
Author: AfBu (https://sketchfab.com/afbu)
License: CC-BY-SA-4.0 (http://creativecommons.org/licenses/by-sa/4.0/)
Source: https://sketchfab.com/3d-models/quadronic-250-computer-that-never-existed-b945947a2c1d4b18812abe59392f715a
Title: Quadronic 250 - computer that never existed
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/Computer.glb')
  return (
    <group {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]} scale={0.299}>
        <group rotation={[Math.PI / 2, 0, 0]}>
          <mesh geometry={nodes.Object_4.geometry} material={materials.Beige_Plastic} />
          <mesh geometry={nodes.Object_5.geometry} material={materials.Black_Plastic} />
          <mesh geometry={nodes.Object_6.geometry} material={materials.Shiny_Metal} />
          <mesh geometry={nodes.Object_7.geometry} material={materials.Screen} />
          <mesh geometry={nodes.Object_8.geometry} material={materials.Gray_Plastic} />
          <mesh geometry={nodes.Object_9.geometry} material={materials.Paper} />
          <mesh geometry={nodes.Object_10.geometry} material={materials.Red_Plastic} />
          <mesh geometry={nodes.Object_11.geometry} material={materials.Dark_Plastic} />
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/Computer.glb')
